spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/retrodb}
    username: ${DB_USERNAME:retro}
    password: ${DB_PASSWORD:retro123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
